name: student-dropout-ml
channels:
  - conda-forge
  - defaults

dependencies:
  # =========================
  # Core Language
  # =========================
  - python=3.10

  # =========================
  # Core Scientific Libraries
  # =========================
  - numpy=1.24.3
  - pandas=2.0.3

  # =========================
  # Visualization
  # =========================
  - matplotlib=3.7.2
  - seaborn=0.12.2

  # =========================
  # Machine Learning
  # =========================
  - scikit-learn=1.3.0
  - joblib=1.3.2

  # =========================
  # Deep Learning
  # =========================
  - tensorflow=2.14.0

  # =========================
  # Utility
  # =========================
  - tqdm=4.66.1

  # =========================
  # Pip fallback (jika perlu)
  # =========================
  - pip
